  // ---------- shared site data: the single source of truth for every count and listing
  // on the site. Loaded by BOTH index.html (hero stats in js/home.js) and browse.html
  // (all browse pages in js/app.js), in each case immediately before that page's own
  // script, so `items` / `courseOrder` / `typeOrder` / `typeLabel` are in scope. ----------
  const items = [
    { id: 'g-c1-1-ref-graphs-to-know', course: 'Calculus I', type: 'LectureGuideNotes', sections: ['1.999'], sectionLabel: 'Graphs To Know', resource: true,
      title: 'Graphs To Know', desc: 'Reference sheet: graphs to know.',
      guideFile: null, notesFile: 'Course Materials/Calc 1/Notes/Ch. 1/Graphs To Know.pdf', updated: '2026-01-12' },
    { id: 'g-c1-sc1', course: 'Calculus I', type: 'LectureGuideNotes', sections: ['2.0'], sectionLabel: 'Skills Check 1',
      title: 'Skills Check 1', desc: 'Practice problems and solutions for Skills Check 1.',
      guideFile: 'Course Materials/Calc 1/Skill Checks/Skill Check 1/Skills Check 1 Practice.pdf', notesFile: 'Course Materials/Calc 1/Skill Checks/Skill Check 1/Skills Check 1 Practice_Solutions.pdf', updated: '2026-02-09' },
    { id: 'g-c1-2.2', course: 'Calculus I', type: 'LectureGuideNotes', sections: ['2.2'], sectionLabel: 'Limits (An Intuitive Approach)',
      title: '2.2 Limits (An Intuitive Approach) — Guide & Notes', desc: 'Guide and notes covering limits (an intuitive approach).',
      guideFile: 'Course Materials/Calc 1/Notes/Ch. 2/2.2 Limits (An Intuitive Approach)_Guide.pdf', notesFile: 'Course Materials/Calc 1/Notes/Ch. 2/2.2 Limits (An Intuitive Approach)_Notes.pdf', updated: '2026-01-26' },
    { id: 'w-c1-2.2-std', course: 'Calculus I', type: 'Worksheet', subtype: 'Standard', sections: ['2.2'], sectionLabel: 'Limits (An Intuitive Approach)',
      title: '2.2 Limits (An Intuitive Approach)', desc: 'Practice set covering limits (an intuitive approach).',
      worksheetFile: 'Course Materials/Calc 1/Notes/Ch. 2/Worksheets/2.2 Worksheet.pdf', solutionsFile: 'Course Materials/Calc 1/Notes/Ch. 2/Worksheets/2.2 Worksheet_Solutions.pdf', updated: '2026-02-09' },
    { id: 'g-c1-2.3.1', course: 'Calculus I', type: 'LectureGuideNotes', sections: ['2.3.1'], sectionLabel: 'Computing Limits',
      title: '2.3.1 Computing Limits — Guide & Notes', desc: 'Guide and notes covering computing limits.',
      guideFile: 'Course Materials/Calc 1/Notes/Ch. 2/2.3.1 Computing Limits_Guide.pdf', notesFile: 'Course Materials/Calc 1/Notes/Ch. 2/2.3.1 Computing Limits_Notes.pdf', updated: '2026-02-09' },
    { id: 'w-c1-2.3.1-2.3.2-std', course: 'Calculus I', type: 'Worksheet', subtype: 'Standard', sections: ['2.3.1', '2.3.2'], sectionLabel: 'Computing Limits',
      title: '2.3.1 & 2.3.2 Computing Limits', desc: 'Practice set covering computing limits.',
      worksheetFile: 'Course Materials/Calc 1/Notes/Ch. 2/Worksheets/2.3.1 & 2.3.2 Worksheet.pdf', solutionsFile: 'Course Materials/Calc 1/Notes/Ch. 2/Worksheets/2.3.1 & 2.3.2 Worksheet_Solutions.pdf', updated: '2026-02-23' },
    { id: 'w-c1-2.3.1-std', course: 'Calculus I', type: 'Worksheet', subtype: 'Standard', sections: ['2.3.1'], sectionLabel: 'Limits',
      title: '2.3.1 Limits', desc: 'Practice set covering limits.',
      worksheetFile: 'Course Materials/Calc 1/Notes/Ch. 2/Worksheets/2.3.1 Limits Worksheet.pdf', solutionsFile: 'Course Materials/Calc 1/Notes/Ch. 2/Worksheets/2.3.1 Limits Worksheet_Solutions.pdf', updated: '2026-03-09' },
    { id: 'g-c1-2.3.2', course: 'Calculus I', type: 'LectureGuideNotes', sections: ['2.3.2'], sectionLabel: 'Limits at Infinity',
      title: '2.3.2 Limits at Infinity — Guide & Notes', desc: 'Guide and notes covering limits at infinity.',
      guideFile: 'Course Materials/Calc 1/Notes/Ch. 2/2.3.2 Limits at Infinity_Guide.pdf', notesFile: 'Course Materials/Calc 1/Notes/Ch. 2/2.3.2 Limits at Infinity_Notes.pdf', updated: '2026-02-23' },
    { id: 'g-c1-2.4.1', course: 'Calculus I', type: 'LectureGuideNotes', sections: ['2.4.1'], sectionLabel: 'Continuity',
      title: '2.4.1 Continuity — Guide & Notes', desc: 'Guide and notes covering continuity.',
      guideFile: 'Course Materials/Calc 1/Notes/Ch. 2/2.4.1 Continuity_Guide.pdf', notesFile: 'Course Materials/Calc 1/Notes/Ch. 2/2.4.1 Continuity_Notes.pdf', updated: '2026-03-09' },
    { id: 'w-c1-2.4.1-std', course: 'Calculus I', type: 'Worksheet', subtype: 'Standard', sections: ['2.4.1'], sectionLabel: 'Continutity',
      title: '2.4.1 Continutity', desc: 'Practice set covering continutity.',
      worksheetFile: 'Course Materials/Calc 1/Notes/Ch. 2/Worksheets/2.4.1 Continutity Worksheet.pdf', solutionsFile: 'Course Materials/Calc 1/Notes/Ch. 2/Worksheets/2.4.1 Continutity Worksheet_Solutions.pdf', updated: '2026-01-12' },
    { id: 'g-c1-2.4.2', course: 'Calculus I', type: 'LectureGuideNotes', sections: ['2.4.2'], sectionLabel: 'Intermediate Value Theorem',
      title: '2.4.2 Intermediate Value Theorem — Guide & Notes', desc: 'Guide and notes covering intermediate value theorem.',
      guideFile: 'Course Materials/Calc 1/Notes/Ch. 2/2.4.2 Intermediate Value Theorem_Guide.pdf', notesFile: 'Course Materials/Calc 1/Notes/Ch. 2/2.4.2 Intermediate Value Theorem_Notes.pdf', updated: '2026-01-12' },
    { id: 'w-c1-2.4.2-std', course: 'Calculus I', type: 'Worksheet', subtype: 'Standard', sections: ['2.4.2'], sectionLabel: 'IVT',
      title: '2.4.2 IVT', desc: 'Practice set covering ivt.',
      worksheetFile: 'Course Materials/Calc 1/Notes/Ch. 2/Worksheets/2.4.2 IVT Worksheet.pdf', solutionsFile: 'Course Materials/Calc 1/Notes/Ch. 2/Worksheets/2.4.2 IVT Worksheet_Solutions.pdf', updated: '2026-01-26' },
    { id: 'g-c1-2.5', course: 'Calculus I', type: 'LectureGuideNotes', sections: ['2.5'], sectionLabel: 'Epsilon-Delta Definition of Limits',
      title: '2.5 Epsilon-Delta Definition of Limits — Guide & Notes', desc: 'Guide and notes covering epsilon-delta definition of limits.',
      guideFile: 'Course Materials/Calc 1/Notes/Ch. 2/2.5 Epsilon-Delta Definition of Limits_Guide.pdf', notesFile: 'Course Materials/Calc 1/Notes/Ch. 2/2.5 Epsilon-Delta Definition of Limits_Notes.pdf', updated: '2026-01-26' },
    { id: 'w-c1-2.5-std', course: 'Calculus I', type: 'Worksheet', subtype: 'Standard', sections: ['2.5'], sectionLabel: 'Epsilon-Delta Definition of Limits',
      title: '2.5 Epsilon-Delta Definition of Limits', desc: 'Practice set covering epsilon-delta definition of limits.',
      worksheetFile: 'Course Materials/Calc 1/Notes/Ch. 2/Worksheets/2.5 Worksheet.pdf', solutionsFile: 'Course Materials/Calc 1/Notes/Ch. 2/Worksheets/2.5 Worksheet_Solutions.pdf', updated: '2026-02-09' },
    { id: 'g-c1-sc2', course: 'Calculus I', type: 'LectureGuideNotes', sections: ['3.0'], sectionLabel: 'Skills Check 2',
      title: 'Skills Check 2', desc: 'Practice problems and solutions for Skills Check 2.',
      guideFile: 'Course Materials/Calc 1/Skill Checks/Skill Check 2/Skills Check 2 Practice.pdf', notesFile: 'Course Materials/Calc 1/Skill Checks/Skill Check 2/Skills Check 2 Practice_Solutions.pdf', updated: '2026-02-23' },
    { id: 'g-c1-3.1', course: 'Calculus I', type: 'LectureGuideNotes', sections: ['3.1'], sectionLabel: 'Defining the Derivative',
      title: '3.1 Defining the Derivative — Guide & Notes', desc: 'Guide and notes covering defining the derivative.',
      guideFile: 'Course Materials/Calc 1/Notes/Ch. 3/3.1 Defining the Derivative_Guide.pdf', notesFile: 'Course Materials/Calc 1/Notes/Ch. 3/3.1 Defining the Derivative_Notes.pdf', updated: '2026-02-23' },
    { id: 'w-c1-3.1-std', course: 'Calculus I', type: 'Worksheet', subtype: 'Standard', sections: ['3.1'], sectionLabel: 'Defining the Derivative',
      title: '3.1 Defining the Derivative', desc: 'Practice set covering defining the derivative.',
      worksheetFile: 'Course Materials/Calc 1/Notes/Ch. 3/Worksheets/3.1 Defining the Derivative Worksheet.pdf', solutionsFile: 'Course Materials/Calc 1/Notes/Ch. 3/Worksheets/3.1 Defining the Derivative Worksheet_Solutions.pdf', updated: '2026-02-23' },
    { id: 'w-c1-3.1-3.2-std', course: 'Calculus I', type: 'Worksheet', subtype: 'Standard', sections: ['3.1', '3.2'], sectionLabel: 'Derivative Function',
      title: '3.1 & 3.2 Derivative Function', desc: 'Practice set covering derivative function.',
      worksheetFile: 'Course Materials/Calc 1/Notes/Ch. 3/Worksheets/3.1&3.2 Derivative Function Worksheet.pdf', solutionsFile: 'Course Materials/Calc 1/Notes/Ch. 3/Worksheets/3.1&3.2 Derivative Function Worksheet_Solutions.pdf', updated: '2026-03-09' },
    { id: 'g-c1-3.2', course: 'Calculus I', type: 'LectureGuideNotes', sections: ['3.2'], sectionLabel: 'The Derivative as a Function',
      title: '3.2 The Derivative as a Function — Guide & Notes', desc: 'Guide and notes covering the derivative as a function.',
      guideFile: 'Course Materials/Calc 1/Notes/Ch. 3/3.2 The Derivative as a Function_Guide.pdf', notesFile: 'Course Materials/Calc 1/Notes/Ch. 3/3.2 The Derivative as a Function_Notes.pdf', updated: '2026-03-09' },
    { id: 'w-c1-3.2-std', course: 'Calculus I', type: 'Worksheet', subtype: 'Standard', sections: ['3.2'], sectionLabel: 'The Derivative as a Function',
      title: '3.2 The Derivative as a Function', desc: 'Practice set covering the derivative as a function.',
      worksheetFile: 'Course Materials/Calc 1/Notes/Ch. 3/Worksheets/3.2 The Derivative as a Function Worksheet.pdf', solutionsFile: 'Course Materials/Calc 1/Notes/Ch. 3/Worksheets/3.2 The Derivative as a Function Worksheet_Solutions.pdf', updated: '2026-01-12' },
    { id: 'w-c1-3.3-std', course: 'Calculus I', type: 'Worksheet', subtype: 'Standard', sections: ['3.3'], sectionLabel: 'Derivatives',
      title: '3.3 Derivatives', desc: 'Practice set covering derivatives.',
      worksheetFile: 'Course Materials/Calc 1/Notes/Ch. 3/Worksheets/3.3 Derivatives Worksheet.pdf', solutionsFile: 'Course Materials/Calc 1/Notes/Ch. 3/Worksheets/3.3 Derivatives Worksheet_Solutions.pdf', updated: '2026-01-26' },
    { id: 'g-c1-3.3.1', course: 'Calculus I', type: 'LectureGuideNotes', sections: ['3.3.1'], sectionLabel: 'Introduction to Differentiation',
      title: '3.3.1 Introduction to Differentiation — Guide & Notes', desc: 'Guide and notes covering introduction to differentiation.',
      guideFile: 'Course Materials/Calc 1/Notes/Ch. 3/3.3.1 Introduction to Differentiation_Guide.pdf', notesFile: 'Course Materials/Calc 1/Notes/Ch. 3/3.3.1 Introduction to Differentiation_Notes.pdf', updated: '2026-01-12' },
    { id: 'w-c1-3.3.1-std', course: 'Calculus I', type: 'Worksheet', subtype: 'Standard', sections: ['3.3.1'], sectionLabel: 'Derivatives',
      title: '3.3.1 Derivatives', desc: 'Practice set covering derivatives.',
      worksheetFile: 'Course Materials/Calc 1/Notes/Ch. 3/Worksheets/3.3.1 Derivatives Worksheet.pdf', solutionsFile: 'Course Materials/Calc 1/Notes/Ch. 3/Worksheets/3.3.1 Derivatives Worksheet_Solutions.pdf', updated: '2026-02-09' },
    { id: 'g-c1-3.3.2', course: 'Calculus I', type: 'LectureGuideNotes', sections: ['3.3.2'], sectionLabel: 'The Product Rule',
      title: '3.3.2 The Product Rule — Guide & Notes', desc: 'Guide and notes covering the product rule.',
      guideFile: 'Course Materials/Calc 1/Notes/Ch. 3/3.3.2 The Product Rule_Guide.pdf', notesFile: 'Course Materials/Calc 1/Notes/Ch. 3/3.3.2 The Product Rule_Notes.pdf', updated: '2026-01-26' },
    { id: 'w-c1-3.3.2-std', course: 'Calculus I', type: 'Worksheet', subtype: 'Standard', sections: ['3.3.2'], sectionLabel: 'Derivatives',
      title: '3.3.2 Derivatives', desc: 'Practice set covering derivatives.',
      worksheetFile: 'Course Materials/Calc 1/Notes/Ch. 3/Worksheets/3.3.2 Derivatives Worksheet.pdf', solutionsFile: 'Course Materials/Calc 1/Notes/Ch. 3/Worksheets/3.3.2 Derivatives Worksheet_Solutions.pdf', updated: '2026-02-23' },
    { id: 'g-c1-3.3.3', course: 'Calculus I', type: 'LectureGuideNotes', sections: ['3.3.3'], sectionLabel: 'The Quotient Rule',
      title: '3.3.3 The Quotient Rule — Guide & Notes', desc: 'Guide and notes covering the quotient rule.',
      guideFile: 'Course Materials/Calc 1/Notes/Ch. 3/3.3.3 The Quotient Rule_Guide.pdf', notesFile: 'Course Materials/Calc 1/Notes/Ch. 3/3.3.3 The Quotient Rule_Notes.pdf', updated: '2026-02-09' },
    { id: 'w-c1-3.3.3-std', course: 'Calculus I', type: 'Worksheet', subtype: 'Standard', sections: ['3.3.3'], sectionLabel: 'Derivatives',
      title: '3.3.3 Derivatives', desc: 'Practice set covering derivatives.',
      worksheetFile: 'Course Materials/Calc 1/Notes/Ch. 3/Worksheets/3.3.3 Derivatives Worksheet.pdf', solutionsFile: 'Course Materials/Calc 1/Notes/Ch. 3/Worksheets/3.3.3 Derivatives Worksheet_Solutions.pdf', updated: '2026-03-09' },
    { id: 'g-c1-3.5', course: 'Calculus I', type: 'LectureGuideNotes', sections: ['3.5'], sectionLabel: 'Derivatives of Trigonometric Functions',
      title: '3.5 Derivatives of Trigonometric Functions — Guide & Notes', desc: 'Guide and notes covering derivatives of trigonometric functions.',
      guideFile: 'Course Materials/Calc 1/Notes/Ch. 3/3.5 Derivatives of Trigonometric Functions_Guide.pdf', notesFile: 'Course Materials/Calc 1/Notes/Ch. 3/3.5 Derivatives of Trigonometric Functions_Notes.pdf', updated: '2026-02-23' },
    { id: 'w-c1-3.5-std', course: 'Calculus I', type: 'Worksheet', subtype: 'Standard', sections: ['3.5'], sectionLabel: 'Derivatives',
      title: '3.5 Derivatives', desc: 'Practice set covering derivatives.',
      worksheetFile: 'Course Materials/Calc 1/Notes/Ch. 3/Worksheets/3.5 Derivatives Worksheet.pdf', solutionsFile: 'Course Materials/Calc 1/Notes/Ch. 3/Worksheets/3.5 Derivatives Worksheet_Solutions.pdf', updated: '2026-01-12' },
    { id: 'g-c1-3.6', course: 'Calculus I', type: 'LectureGuideNotes', sections: ['3.6'], sectionLabel: 'The Chain Rule',
      title: '3.6 The Chain Rule — Guide & Notes', desc: 'Guide and notes covering the chain rule.',
      guideFile: 'Course Materials/Calc 1/Notes/Ch. 3/3.6 The Chain Rule_Guide.pdf', notesFile: 'Course Materials/Calc 1/Notes/Ch. 3/3.6 The Chain Rule_Notes.pdf', updated: '2026-03-09' },
    { id: 'w-c1-3.6-std', course: 'Calculus I', type: 'Worksheet', subtype: 'Standard', sections: ['3.6'], sectionLabel: 'Chain Rule',
      title: '3.6 Chain Rule', desc: 'Practice set covering chain rule.',
      worksheetFile: 'Course Materials/Calc 1/Notes/Ch. 3/Worksheets/3.6 Chain Rule Worksheet.pdf', solutionsFile: 'Course Materials/Calc 1/Notes/Ch. 3/Worksheets/3.6 Chain Rule Worksheet_Solutions.pdf', updated: '2026-01-26' },
    { id: 'g-c1-3.8', course: 'Calculus I', type: 'LectureGuideNotes', sections: ['3.8'], sectionLabel: 'Implicit Differentiation',
      title: '3.8 Implicit Differentiation — Guide & Notes', desc: 'Guide and notes covering implicit differentiation.',
      guideFile: 'Course Materials/Calc 1/Notes/Ch. 3/3.8 Implicit Differentiation_Guide.pdf', notesFile: 'Course Materials/Calc 1/Notes/Ch. 3/3.8 Implicit Differentiation_Notes.pdf', updated: '2026-01-12' },
    { id: 'w-c1-3.8-std', course: 'Calculus I', type: 'Worksheet', subtype: 'Standard', sections: ['3.8'], sectionLabel: 'Implicit Differentiation',
      title: '3.8 Implicit Differentiation', desc: 'Practice set covering implicit differentiation.',
      worksheetFile: 'Course Materials/Calc 1/Notes/Ch. 3/Worksheets/3.8 Implicit Differentiation Worksheet.pdf', solutionsFile: 'Course Materials/Calc 1/Notes/Ch. 3/Worksheets/3.8 Implicit Differentiation Worksheet_Solutions.pdf', updated: '2026-02-09' },
    { id: 'g-c1-3.9', course: 'Calculus I', type: 'LectureGuideNotes', sections: ['3.9'], sectionLabel: 'Derivatives of Exponential and Logarithmic Functions',
      title: '3.9 Derivatives of Exponential and Logarithmic Functions — Guide & Notes', desc: 'Guide and notes covering derivatives of exponential and logarithmic functions.',
      guideFile: 'Course Materials/Calc 1/Notes/Ch. 3/3.9 Derivatives of Exponential and Logarithmic Functions_Guide.pdf', notesFile: 'Course Materials/Calc 1/Notes/Ch. 3/3.9 Derivatives of Exponential and Logarithmic Functions_Notes.pdf', updated: '2026-01-26' },
    { id: 'w-c1-3.9-std', course: 'Calculus I', type: 'Worksheet', subtype: 'Standard', sections: ['3.9'], sectionLabel: 'Exponential & Logarithmic Derivatives',
      title: '3.9 Exponential & Logarithmic Derivatives', desc: 'Practice set covering exponential & logarithmic derivatives.',
      worksheetFile: 'Course Materials/Calc 1/Notes/Ch. 3/Worksheets/3.9 Exponential & Logarithmic Derivatives Worksheet.pdf', solutionsFile: 'Course Materials/Calc 1/Notes/Ch. 3/Worksheets/3.9 Exponential & Logarithmic Derivatives Worksheet_Solutions.pdf', updated: '2026-02-23' },
    { id: 'g-c1-3-ref-differentiation-rules', course: 'Calculus I', type: 'LectureGuideNotes', sections: ['3.999'], sectionLabel: 'Differentiation Rules',
      title: 'Differentiation Rules', desc: 'Reference sheet: differentiation rules.',
      guideFile: null, notesFile: 'Course Materials/Calc 1/Notes/Ch. 3/Differentiation Rules.pdf', updated: '2026-02-09' },
    { id: 'g-c1-sc3', course: 'Calculus I', type: 'LectureGuideNotes', sections: ['4.0'], sectionLabel: 'Skills Check 3',
      title: 'Skills Check 3', desc: 'Practice problems and solutions for Skills Check 3.',
      guideFile: 'Course Materials/Calc 1/Skill Checks/Skill Check 3/Skills Check 3 Practice.pdf', notesFile: 'Course Materials/Calc 1/Skill Checks/Skill Check 3/Skills Check 3 Practice_Solutions.pdf', updated: '2026-03-09' },
    { id: 'g-c1-4.1', course: 'Calculus I', type: 'LectureGuideNotes', sections: ['4.1'], sectionLabel: 'Related Rates',
      title: '4.1 Related Rates — Guide & Notes', desc: 'Guide and notes covering related rates.',
      guideFile: 'Course Materials/Calc 1/Notes/Ch. 4/4.1 Related Rates_Guide.pdf', notesFile: 'Course Materials/Calc 1/Notes/Ch. 4/4.1 Related Rates_Notes.pdf', updated: '2026-03-09' },
    { id: 'w-c1-4.1-std', course: 'Calculus I', type: 'Worksheet', subtype: 'Standard', sections: ['4.1'], sectionLabel: 'Related Rates',
      title: '4.1 Related Rates', desc: 'Practice set covering related rates.',
      worksheetFile: 'Course Materials/Calc 1/Notes/Ch. 4/Worksheets/4.1 Related Rates Worksheet.pdf', solutionsFile: 'Course Materials/Calc 1/Notes/Ch. 4/Worksheets/4.1 Related Rates Worksheet_Solutions.pdf', updated: '2026-02-23' },
    { id: 'g-c1-4.2', course: 'Calculus I', type: 'LectureGuideNotes', sections: ['4.2'], sectionLabel: 'Linear Approximations & Differentials',
      title: '4.2 Linear Approximations & Differentials — Guide & Notes', desc: 'Guide and notes covering linear approximations & differentials.',
      guideFile: 'Course Materials/Calc 1/Notes/Ch. 4/4.2 Linear Approximations & Differentials_Guide.pdf', notesFile: 'Course Materials/Calc 1/Notes/Ch. 4/4.2 Linear Approximations & Differentials_Notes.pdf', updated: '2026-01-26' },
    { id: 'w-c1-4.2-std', course: 'Calculus I', type: 'Worksheet', subtype: 'Standard', sections: ['4.2'], sectionLabel: 'Linear Approximations & Differentials',
      title: '4.2 Linear Approximations & Differentials', desc: 'Practice set covering linear approximations & differentials.',
      worksheetFile: 'Course Materials/Calc 1/Notes/Ch. 4/Worksheets/4.2 Linear Approximations & Differentials Worksheet.pdf', solutionsFile: 'Course Materials/Calc 1/Notes/Ch. 4/Worksheets/4.2 Linear Approximations & Differentials Worksheet_Solutions.pdf', updated: '2026-01-12' },
    { id: 'g-c1-4.3', course: 'Calculus I', type: 'LectureGuideNotes', sections: ['4.3'], sectionLabel: 'Maximum & Minimum Values',
      title: '4.3 Maximum & Minimum Values — Guide & Notes', desc: 'Guide and notes covering maximum & minimum values.',
      guideFile: 'Course Materials/Calc 1/Notes/Ch. 4/4.3 Maximum & Minimum Values_Guide.pdf', notesFile: 'Course Materials/Calc 1/Notes/Ch. 4/4.3 Maximum & Minimum Values_Notes.pdf', updated: '2026-02-09' },
    { id: 'w-c1-4.3-std', course: 'Calculus I', type: 'Worksheet', subtype: 'Standard', sections: ['4.3'], sectionLabel: 'Maximum & Minimum Values',
      title: '4.3 Maximum & Minimum Values', desc: 'Practice set covering maximum & minimum values.',
      worksheetFile: 'Course Materials/Calc 1/Notes/Ch. 4/Worksheets/4.3 Maximum & Minimum Values Worksheet.pdf', solutionsFile: 'Course Materials/Calc 1/Notes/Ch. 4/Worksheets/4.3 Maximum & Minimum Values Worksheet_Solutions.pdf', updated: '2026-01-26' },
    { id: 'g-c1-4.4', course: 'Calculus I', type: 'LectureGuideNotes', sections: ['4.4'], sectionLabel: 'The Mean Value Theorem',
      title: '4.4 The Mean Value Theorem — Guide & Notes', desc: 'Guide and notes covering the mean value theorem.',
      guideFile: 'Course Materials/Calc 1/Notes/Ch. 4/4.4 The Mean Value Theorem_Guide.pdf', notesFile: 'Course Materials/Calc 1/Notes/Ch. 4/4.4 The Mean Value Theorem_Notes.pdf', updated: '2026-02-23' },
    { id: 'w-c1-4.4-std', course: 'Calculus I', type: 'Worksheet', subtype: 'Standard', sections: ['4.4'], sectionLabel: 'MVT',
      title: '4.4 MVT', desc: 'Practice set covering mvt.',
      worksheetFile: 'Course Materials/Calc 1/Notes/Ch. 4/Worksheets/4.4 MVT Worksheet.pdf', solutionsFile: 'Course Materials/Calc 1/Notes/Ch. 4/Worksheets/4.4 MVT Worksheet_Solutions.pdf', updated: '2026-02-09' },
    { id: 'g-c1-4.5', course: 'Calculus I', type: 'LectureGuideNotes', sections: ['4.5'], sectionLabel: 'Derivatives & the Shape of a Graph',
      title: '4.5 Derivatives & the Shape of a Graph — Guide & Notes', desc: 'Guide and notes covering derivatives & the shape of a graph.',
      guideFile: 'Course Materials/Calc 1/Notes/Ch. 4/4.5 Derivatives & the Shape of a Graph_Guide.pdf', notesFile: 'Course Materials/Calc 1/Notes/Ch. 4/4.5 Derivatives & the Shape of a Graph_Notes.pdf', updated: '2026-03-09' },
    { id: 'w-c1-4.5-std', course: 'Calculus I', type: 'Worksheet', subtype: 'Standard', sections: ['4.5'], sectionLabel: 'Derivatives & the Shape of a Graph',
      title: '4.5 Derivatives & the Shape of a Graph', desc: 'Practice set covering derivatives & the shape of a graph.',
      worksheetFile: 'Course Materials/Calc 1/Notes/Ch. 4/Worksheets/4.5 Worksheet.pdf', solutionsFile: 'Course Materials/Calc 1/Notes/Ch. 4/Worksheets/4.5 Worksheet_Solutions.pdf', updated: '2026-02-23' },
    { id: 'g-c1-4.7', course: 'Calculus I', type: 'LectureGuideNotes', sections: ['4.7'], sectionLabel: 'Optimization',
      title: '4.7 Optimization — Guide & Notes', desc: 'Guide and notes covering optimization.',
      guideFile: 'Course Materials/Calc 1/Notes/Ch. 4/4.7 Optimization_Guide.pdf', notesFile: 'Course Materials/Calc 1/Notes/Ch. 4/4.7 Optimization_Notes.pdf', updated: '2026-01-12' },
    { id: 'w-c1-4.7-std', course: 'Calculus I', type: 'Worksheet', subtype: 'Standard', sections: ['4.7'], sectionLabel: 'Optimization',
      title: '4.7 Optimization', desc: 'Practice set covering optimization.',
      worksheetFile: 'Course Materials/Calc 1/Notes/Ch. 4/Worksheets/4.7 Optimization Worksheet.pdf', solutionsFile: 'Course Materials/Calc 1/Notes/Ch. 4/Worksheets/4.7 Optimization Worksheet_Solutions.pdf', updated: '2026-03-09' },
    { id: 'g-c1-4.8', course: 'Calculus I', type: 'LectureGuideNotes', sections: ['4.8'], sectionLabel: 'L\'Hopital\'s Rule; Indeterminate Forms',
      title: '4.8 L\'Hopital\'s Rule; Indeterminate Forms — Guide & Notes', desc: 'Guide and notes covering l\'hopital\'s rule; indeterminate forms.',
      guideFile: 'Course Materials/Calc 1/Notes/Ch. 4/4.8 L\'Hopital\'s Rule; Indeterminate Forms_Guide.pdf', notesFile: 'Course Materials/Calc 1/Notes/Ch. 4/4.8 L\'Hopital\'s Rule; Indeterminate Forms_Notes.pdf', updated: '2026-01-26' },
    { id: 'w-c1-4.8-std', course: 'Calculus I', type: 'Worksheet', subtype: 'Standard', sections: ['4.8'], sectionLabel: 'L\'Hopital\'s Rule',
      title: '4.8 L\'Hopital\'s Rule', desc: 'Practice set covering l\'hopital\'s rule.',
      worksheetFile: 'Course Materials/Calc 1/Notes/Ch. 4/Worksheets/4.8 L\'Hopital\'s Rule Worksheet.pdf', solutionsFile: 'Course Materials/Calc 1/Notes/Ch. 4/Worksheets/4.8 L\'Hopital\'s Rule Worksheet_Solutions.pdf', updated: '2026-01-12' },
    { id: 'g-c1-4.9', course: 'Calculus I', type: 'LectureGuideNotes', sections: ['4.9'], sectionLabel: 'Newton\'s Method',
      title: '4.9 Newton\'s Method — Guide & Notes', desc: 'Guide and notes covering newton\'s method.',
      guideFile: 'Course Materials/Calc 1/Notes/Ch. 4/4.9 Newton\'s Method_Guide.pdf', notesFile: 'Course Materials/Calc 1/Notes/Ch. 4/4.9 Newton\'s Method_Notes.pdf', updated: '2026-02-09' },
    { id: 'w-c1-4.9-std', course: 'Calculus I', type: 'Worksheet', subtype: 'Standard', sections: ['4.9'], sectionLabel: 'Newton\'s Method',
      title: '4.9 Newton\'s Method', desc: 'Practice set covering newton\'s method.',
      worksheetFile: 'Course Materials/Calc 1/Notes/Ch. 4/Worksheets/4.9 Newton\'s Method Worksheet.pdf', solutionsFile: 'Course Materials/Calc 1/Notes/Ch. 4/Worksheets/4.9 Newton\'s Method Worksheet_Solutions.pdf', updated: '2026-01-26' },
    { id: 'g-c1-4.10', course: 'Calculus I', type: 'LectureGuideNotes', sections: ['4.10'], sectionLabel: 'Antiderivatives',
      title: '4.10 Antiderivatives — Guide & Notes', desc: 'Guide and notes covering antiderivatives.',
      guideFile: 'Course Materials/Calc 1/Notes/Ch. 4/4.10 Antiderivatives_Guide.pdf', notesFile: 'Course Materials/Calc 1/Notes/Ch. 4/4.10 Antiderivatives_Notes.pdf', updated: '2026-01-12' },
    { id: 'w-c1-4.10-std', course: 'Calculus I', type: 'Worksheet', subtype: 'Standard', sections: ['4.10'], sectionLabel: 'Antiderivatives',
      title: '4.10 Antiderivatives', desc: 'Practice set covering antiderivatives.',
      worksheetFile: 'Course Materials/Calc 1/Notes/Ch. 4/Worksheets/4.10 Antiderivatives Worksheet.pdf', solutionsFile: 'Course Materials/Calc 1/Notes/Ch. 4/Worksheets/4.10 Antiderivatives Worksheet_Solutions.pdf', updated: '2026-03-09' },
    { id: 'g-c1-5.1', course: 'Calculus I', type: 'LectureGuideNotes', sections: ['5.1'], sectionLabel: 'Approximating Areas',
      title: '5.1 Approximating Areas — Guide & Notes', desc: 'Guide and notes covering approximating areas.',
      guideFile: 'Course Materials/Calc 1/Notes/Ch. 5/5.1 Approximating Areas_Guide.pdf', notesFile: 'Course Materials/Calc 1/Notes/Ch. 5/5.1 Approximating Areas_Notes.pdf', updated: '2026-02-09' },
    { id: 'w-c1-5.1-std', course: 'Calculus I', type: 'Worksheet', subtype: 'Standard', sections: ['5.1'], sectionLabel: 'Riemann Sum',
      title: '5.1 Riemann Sum', desc: 'Practice set covering riemann sum.',
      worksheetFile: 'Course Materials/Calc 1/Notes/Ch. 5/Worksheets/5.1 Riemann Sum Worksheet.pdf', solutionsFile: 'Course Materials/Calc 1/Notes/Ch. 5/Worksheets/5.1 Riemann Sum Worksheet_Solutions.pdf', updated: '2026-01-26' },
    { id: 'g-c1-5.2.1', course: 'Calculus I', type: 'LectureGuideNotes', sections: ['5.2.1'], sectionLabel: 'The Definite Integral',
      title: '5.2.1 The Definite Integral — Guide & Notes', desc: 'Guide and notes covering the definite integral.',
      guideFile: 'Course Materials/Calc 1/Notes/Ch. 5/5.2.1 The Definite Integral_Guide.pdf', notesFile: 'Course Materials/Calc 1/Notes/Ch. 5/5.2.1 The Definite Integral_Notes.pdf', updated: '2026-02-23' },
    { id: 'w-c1-5.2.1-std', course: 'Calculus I', type: 'Worksheet', subtype: 'Standard', sections: ['5.2.1'], sectionLabel: 'Definite Integral',
      title: '5.2.1 Definite Integral', desc: 'Practice set covering definite integral.',
      worksheetFile: 'Course Materials/Calc 1/Notes/Ch. 5/Worksheets/5.2.1 Definite Integral Worksheet.pdf', solutionsFile: 'Course Materials/Calc 1/Notes/Ch. 5/Worksheets/5.2.1 Definite Integral Worksheet_Solutions.pdf', updated: '2026-02-09' },
    { id: 'g-c1-5.2.2', course: 'Calculus I', type: 'LectureGuideNotes', sections: ['5.2.2'], sectionLabel: 'Properties of the Definite Integral',
      title: '5.2.2 Properties of the Definite Integral — Guide & Notes', desc: 'Guide and notes covering properties of the definite integral.',
      guideFile: 'Course Materials/Calc 1/Notes/Ch. 5/5.2.2 Properties of the Definite Integral_Guide.pdf', notesFile: 'Course Materials/Calc 1/Notes/Ch. 5/5.2.2 Properties of the Definite Integral_Notes.pdf', updated: '2026-03-09' },
    { id: 'w-c1-5.2.2-std', course: 'Calculus I', type: 'Worksheet', subtype: 'Standard', sections: ['5.2.2'], sectionLabel: 'Properties of the Definite Integral',
      title: '5.2.2 Properties of the Definite Integral', desc: 'Practice set covering properties of the definite integral.',
      worksheetFile: 'Course Materials/Calc 1/Notes/Ch. 5/Worksheets/5.2.2 Properties of the Definite Integral Worksheet.pdf', solutionsFile: 'Course Materials/Calc 1/Notes/Ch. 5/Worksheets/5.2.2 Properties of the Definite Integral Worksheet_Solutions.pdf', updated: '2026-02-23' },
    { id: 'g-c1-5.2.3', course: 'Calculus I', type: 'LectureGuideNotes', sections: ['5.2.3'], sectionLabel: 'Average Value',
      title: '5.2.3 Average Value — Guide & Notes', desc: 'Guide and notes covering average value.',
      guideFile: 'Course Materials/Calc 1/Notes/Ch. 5/5.2.3 Average Value_Guide.pdf', notesFile: 'Course Materials/Calc 1/Notes/Ch. 5/5.2.3 Average Value_Notes.pdf', updated: '2026-01-12' },
    { id: 'w-c1-5.2.3-std', course: 'Calculus I', type: 'Worksheet', subtype: 'Standard', sections: ['5.2.3'], sectionLabel: 'Average Value',
      title: '5.2.3 Average Value', desc: 'Practice set covering average value.',
      worksheetFile: 'Course Materials/Calc 1/Notes/Ch. 5/Worksheets/5.2.3 Average Value Worksheet.pdf', solutionsFile: 'Course Materials/Calc 1/Notes/Ch. 5/Worksheets/5.2.3 Average Value Worksheet_Solutions.pdf', updated: '2026-03-09' },
    { id: 'g-c1-5.3.1', course: 'Calculus I', type: 'LectureGuideNotes', sections: ['5.3.1'], sectionLabel: 'The Fundamental Theorem of Calculus',
      title: '5.3.1 The Fundamental Theorem of Calculus — Guide & Notes', desc: 'Guide and notes covering the fundamental theorem of calculus.',
      guideFile: 'Course Materials/Calc 1/Notes/Ch. 5/5.3.1 The Fundamental Theorem of Calculus_Guide.pdf', notesFile: 'Course Materials/Calc 1/Notes/Ch. 5/5.3.1 The Fundamental Theorem of Calculus_Notes.pdf', updated: '2026-01-26' },
    { id: 'w-c1-5.3.1-std', course: 'Calculus I', type: 'Worksheet', subtype: 'Standard', sections: ['5.3.1'], sectionLabel: 'The Fundamental Theorem',
      title: '5.3.1 The Fundamental Theorem', desc: 'Practice set covering the fundamental theorem.',
      worksheetFile: 'Course Materials/Calc 1/Notes/Ch. 5/Worksheets/5.3.1 The Fundamental Theorem Worksheet.pdf', solutionsFile: 'Course Materials/Calc 1/Notes/Ch. 5/Worksheets/5.3.1 The Fundamental Theorem Worksheet_Solutions.pdf', updated: '2026-01-12' },
    { id: 'g-c1-5.3.2', course: 'Calculus I', type: 'LectureGuideNotes', sections: ['5.3.2'], sectionLabel: 'Definite & Indefinite Integrals',
      title: '5.3.2 Definite & Indefinite Integrals — Guide & Notes', desc: 'Guide and notes covering definite & indefinite integrals.',
      guideFile: 'Course Materials/Calc 1/Notes/Ch. 5/5.3.2 Definite & Indefinite Integrals_Guide.pdf', notesFile: 'Course Materials/Calc 1/Notes/Ch. 5/5.3.2 Definite & Indefinite Integrals_Notes.pdf', updated: '2026-02-09' },
    { id: 'w-c1-5.3.2-std', course: 'Calculus I', type: 'Worksheet', subtype: 'Standard', sections: ['5.3.2'], sectionLabel: 'Integration',
      title: '5.3.2 Integration', desc: 'Practice set covering integration.',
      worksheetFile: 'Course Materials/Calc 1/Notes/Ch. 5/Worksheets/5.3.2 Integration Worksheet.pdf', solutionsFile: 'Course Materials/Calc 1/Notes/Ch. 5/Worksheets/5.3.2 Integration Worksheet_Solutions.pdf', updated: '2026-01-26' },
    { id: 'g-c1-5.4', course: 'Calculus I', type: 'LectureGuideNotes', sections: ['5.4'], sectionLabel: 'Applications of Integration',
      title: '5.4 Applications of Integration — Guide & Notes', desc: 'Guide and notes covering applications of integration.',
      guideFile: 'Course Materials/Calc 1/Notes/Ch. 5/5.4 Applications of Integration_Guide.pdf', notesFile: 'Course Materials/Calc 1/Notes/Ch. 5/5.4 Applications of Integration_Notes.pdf', updated: '2026-02-23' },
    { id: 'w-c1-5.4-std', course: 'Calculus I', type: 'Worksheet', subtype: 'Standard', sections: ['5.4'], sectionLabel: 'Applications of Integration',
      title: '5.4 Applications of Integration', desc: 'Practice set covering applications of integration.',
      worksheetFile: 'Course Materials/Calc 1/Notes/Ch. 5/Worksheets/5.4 Applications of Integration Worksheet.pdf', solutionsFile: 'Course Materials/Calc 1/Notes/Ch. 5/Worksheets/5.4 Applications of Integration Worksheet_Solutions.pdf', updated: '2026-02-09' },
    { id: 'w-c1-5.5-std', course: 'Calculus I', type: 'Worksheet', subtype: 'Standard', sections: ['5.5'], sectionLabel: 'Substitution',
      title: '5.5 Substitution', desc: 'Practice set covering substitution.',
      worksheetFile: 'Course Materials/Calc 1/Notes/Ch. 5/Worksheets/5.5 Substitution Worksheet.pdf', solutionsFile: 'Course Materials/Calc 1/Notes/Ch. 5/Worksheets/5.5 Substitution Worksheet_Solutions.pdf', updated: '2026-02-23' },
    { id: 'g-c1-5.5.1', course: 'Calculus I', type: 'LectureGuideNotes', sections: ['5.5.1'], sectionLabel: 'Integration by Substitution (Indefinite Integrals)',
      title: '5.5.1 Integration by Substitution (Indefinite Integrals) — Guide & Notes', desc: 'Guide and notes covering integration by substitution (indefinite integrals).',
      guideFile: 'Course Materials/Calc 1/Notes/Ch. 5/5.5.1 Integration by Substitution (Indefinite Integrals)_Guide.pdf', notesFile: 'Course Materials/Calc 1/Notes/Ch. 5/5.5.1 Integration by Substitution (Indefinite Integrals)_Notes.pdf', updated: '2026-03-09' },
    { id: 'w-c1-5.5.1-std', course: 'Calculus I', type: 'Worksheet', subtype: 'Standard', sections: ['5.5.1'], sectionLabel: 'Substitution (Indefinite Integrals)',
      title: '5.5.1 Substitution (Indefinite Integrals)', desc: 'Practice set covering substitution (indefinite integrals).',
      worksheetFile: 'Course Materials/Calc 1/Notes/Ch. 5/Worksheets/5.5.1 Substitution (Indefinite Integrals) Worksheet.pdf', solutionsFile: 'Course Materials/Calc 1/Notes/Ch. 5/Worksheets/5.5.1 Substitution (Indefinite Integrals) Worksheet_Solutions.pdf', updated: '2026-03-09' },
    { id: 'g-c1-5.5.2', course: 'Calculus I', type: 'LectureGuideNotes', sections: ['5.5.2'], sectionLabel: 'Integration by Substitution (Definite Integrals)',
      title: '5.5.2 Integration by Substitution (Definite Integrals) — Guide & Notes', desc: 'Guide and notes covering integration by substitution (definite integrals).',
      guideFile: 'Course Materials/Calc 1/Notes/Ch. 5/5.5.2 Integration by Substitution (Definite Integrals)_Guide.pdf', notesFile: 'Course Materials/Calc 1/Notes/Ch. 5/5.5.2 Integration by Substitution (Definite Integrals)_Notes.pdf', updated: '2026-01-12' },
    { id: 'w-c1-5.5.2-std', course: 'Calculus I', type: 'Worksheet', subtype: 'Standard', sections: ['5.5.2'], sectionLabel: 'Substitution (Definite Integrals)',
      title: '5.5.2 Substitution (Definite Integrals)', desc: 'Practice set covering substitution (definite integrals).',
      worksheetFile: 'Course Materials/Calc 1/Notes/Ch. 5/Worksheets/5.5.2 Substitution (Definite Integrals) Worksheet.pdf', solutionsFile: 'Course Materials/Calc 1/Notes/Ch. 5/Worksheets/5.5.2 Substitution (Definite Integrals) Worksheet_Solutions.pdf', updated: '2026-01-12' },
    { id: 'w-c1-5.9-std', course: 'Calculus I', type: 'Worksheet', subtype: 'Standard', sections: ['5.9'], sectionLabel: 'Summary of Integration',
      title: '5.9 Summary of Integration', desc: 'Practice set covering summary of integration.',
      worksheetFile: 'Course Materials/Calc 1/Notes/Ch. 5/Worksheets/Summary of Integration Worksheet.pdf', solutionsFile: 'Course Materials/Calc 1/Notes/Ch. 5/Worksheets/Summary of Integration Worksheet_Solutions.pdf', updated: '2026-01-26' },
    { id: 'w-c1-2.2-ble', course: 'Calculus I', type: 'Worksheet', subtype: 'Blended', sections: ['2.2'], sectionLabel: 'Limits from Graphs',
      title: '2.2 Limits from Graphs (Blended/Honors)', desc: 'Extended Blended/Honors practice set covering limits from graphs.',
      worksheetFile: 'Course Materials/Calc 1/Blended Sessions/Unit 1/2.2 Limits from Graphs.pdf', solutionsFile: 'Course Materials/Calc 1/Blended Sessions/Unit 1/2.2 Limits from Graphs_Solutions.pdf', updated: '2026-01-19' },
    { id: 'w-c1-2.3-ble', course: 'Calculus I', type: 'Worksheet', subtype: 'Blended', sections: ['2.3'], sectionLabel: 'Limit Challenge Problems',
      title: '2.3 Limit Challenge Problems (Blended/Honors)', desc: 'Extended Blended/Honors practice set covering limit challenge problems.',
      worksheetFile: 'Course Materials/Calc 1/Blended Sessions/Unit 1/2.3 Limit Challenge Problems.pdf', solutionsFile: 'Course Materials/Calc 1/Blended Sessions/Unit 1/2.3 Limit Challenge Problems_Solutions.pdf', updated: '2026-02-16' },
    { id: 'w-c1-2.3.1-ble', course: 'Calculus I', type: 'Worksheet', subtype: 'Blended', sections: ['2.3.1'], sectionLabel: 'Strategies for Computing Limits',
      title: '2.3.1 Strategies for Computing Limits (Blended/Honors)', desc: 'Extended Blended/Honors practice set covering strategies for computing limits.',
      worksheetFile: 'Course Materials/Calc 1/Blended Sessions/Unit 1/2.3.1 Strategies for Computing Limits.pdf', solutionsFile: 'Course Materials/Calc 1/Blended Sessions/Unit 1/2.3.1 Strategies for Computing Limits_Solutions.pdf', updated: '2026-03-16' },
    { id: 'w-c1-2.4-ble', course: 'Calculus I', type: 'Worksheet', subtype: 'Blended', sections: ['2.4'], sectionLabel: 'Continuity & IVT',
      title: '2.4 Continuity & IVT (Blended/Honors)', desc: 'Extended Blended/Honors practice set covering continuity & ivt.',
      worksheetFile: 'Course Materials/Calc 1/Blended Sessions/Unit 1/2.4 Continuity & IVT.pdf', solutionsFile: 'Course Materials/Calc 1/Blended Sessions/Unit 1/2.4 Continuity & IVT_Solutions.pdf', updated: '2026-01-05' },
    { id: 'w-c1-2.5-ble', course: 'Calculus I', type: 'Worksheet', subtype: 'Blended', sections: ['2.5'], sectionLabel: 'The Precise Definition of a Limit',
      title: '2.5 The Precise Definition of a Limit (Blended/Honors)', desc: 'Extended Blended/Honors practice set covering the precise definition of a limit.',
      worksheetFile: 'Course Materials/Calc 1/Blended Sessions/Unit 1/2.5 The Precise Definition of a Limit.pdf', solutionsFile: 'Course Materials/Calc 1/Blended Sessions/Unit 1/2.5 The Precise Definition of a Limit_Solutions.pdf', updated: '2026-02-02' },
    { id: 'w-c1-sc1-ble', course: 'Calculus I', type: 'Worksheet', subtype: 'Blended', sections: ['2.0'], sectionLabel: 'Skills Check 1',
      title: 'Skills Check 1 (Blended/Honors)', desc: 'Blended/Honors practice and solutions for Skills Check 1.',
      worksheetFile: 'Course Materials/Calc 1/Blended Sessions/Unit 1/Skills Check 1.pdf', solutionsFile: 'Course Materials/Calc 1/Blended Sessions/Unit 1/Skills Check 1_Solutions.pdf', updated: '2026-01-19' },
    { id: 'w-c1-3.3-ble', course: 'Calculus I', type: 'Worksheet', subtype: 'Blended', sections: ['3.3'], sectionLabel: 'Calculating Derivatives & Proof',
      title: '3.3 Calculating Derivatives & Proof (Blended/Honors)', desc: 'Extended Blended/Honors practice set covering calculating derivatives & proof.',
      worksheetFile: 'Course Materials/Calc 1/Blended Sessions/Unit 2/3.3 Calculating Derivatives & Proof.pdf', solutionsFile: 'Course Materials/Calc 1/Blended Sessions/Unit 2/3.3 Calculating Derivatives & Proof_Solutions.pdf', updated: '2026-02-16' },
    { id: 'w-c1-3.3.1-ble', course: 'Calculus I', type: 'Worksheet', subtype: 'Blended', sections: ['3.3.1'], sectionLabel: 'Derivatives and Notation',
      title: '3.3.1 Derivatives and Notation (Blended/Honors)', desc: 'Extended Blended/Honors practice set covering derivatives and notation.',
      worksheetFile: 'Course Materials/Calc 1/Blended Sessions/Unit 2/3.3.1 Derivatives and Notation.pdf', solutionsFile: 'Course Materials/Calc 1/Blended Sessions/Unit 2/3.3.1 Derivatives and Notation_Solutions.pdf', updated: '2026-03-16' },
    { id: 'w-c1-3.5-ble', course: 'Calculus I', type: 'Worksheet', subtype: 'Blended', sections: ['3.5'], sectionLabel: 'Calculating Derivatives & Definition of the Derivative',
      title: '3.5 Calculating Derivatives & Definition of the Derivative (Blended/Honors)', desc: 'Extended Blended/Honors practice set covering calculating derivatives & definition of the derivative.',
      worksheetFile: 'Course Materials/Calc 1/Blended Sessions/Unit 2/3.5 Calculating Derivatives & Definition of the Derivative.pdf', solutionsFile: 'Course Materials/Calc 1/Blended Sessions/Unit 2/3.5 Calculating Derivatives & Definition of the Derivative_Solutions.pdf', updated: '2026-01-05' },
    { id: 'w-c1-3.6-ble', course: 'Calculus I', type: 'Worksheet', subtype: 'Blended', sections: ['3.6'], sectionLabel: 'Calculating Derivatives (Chain Rule) & Definition of the Derivative',
      title: '3.6 Calculating Derivatives (Chain Rule) & Definition of the Derivative (Blended/Honors)', desc: 'Extended Blended/Honors practice set covering calculating derivatives (chain rule) & definition of the derivative.',
      worksheetFile: 'Course Materials/Calc 1/Blended Sessions/Unit 2/3.6 Calculating Derivatives (Chain Rule) & Definition of the Derivative.pdf', solutionsFile: 'Course Materials/Calc 1/Blended Sessions/Unit 2/3.6 Calculating Derivatives (Chain Rule) & Definition of the Derivative_Solutions.pdf', updated: '2026-02-02' },
    { id: 'w-c1-3.8-ble', course: 'Calculus I', type: 'Worksheet', subtype: 'Blended', sections: ['3.8'], sectionLabel: 'Implicit Differentiation',
      title: '3.8 Implicit Differentiation (Blended/Honors)', desc: 'Extended Blended/Honors practice set covering implicit differentiation.',
      worksheetFile: 'Course Materials/Calc 1/Blended Sessions/Unit 2/3.8 Implicit Differentiation.pdf', solutionsFile: 'Course Materials/Calc 1/Blended Sessions/Unit 2/3.8 Implicit Differentiation_Solutions.pdf', updated: '2026-01-19' },
    { id: 'w-c1-4.1-ble', course: 'Calculus I', type: 'Worksheet', subtype: 'Blended', sections: ['4.1'], sectionLabel: 'Related Rates',
      title: '4.1 Related Rates (Blended/Honors)', desc: 'Extended Blended/Honors practice set covering related rates.',
      worksheetFile: 'Course Materials/Calc 1/Blended Sessions/Unit 2/4.1 Related Rates.pdf', solutionsFile: 'Course Materials/Calc 1/Blended Sessions/Unit 2/4.1 Related Rates_Solutions.pdf', updated: '2026-02-16' },
    { id: 'w-c1-sc2-ble', course: 'Calculus I', type: 'Worksheet', subtype: 'Blended', sections: ['3.0'], sectionLabel: 'Skills Check 2',
      title: 'Skills Check 2 (Blended/Honors)', desc: 'Blended/Honors practice and solutions for Skills Check 2.',
      worksheetFile: 'Course Materials/Calc 1/Blended Sessions/Unit 2/Skills Check 2.pdf', solutionsFile: 'Course Materials/Calc 1/Blended Sessions/Unit 2/Skills Check 2_Solutions.pdf', updated: '2026-03-16' },
    { id: 'w-c1-4.3-ble', course: 'Calculus I', type: 'Worksheet', subtype: 'Blended', sections: ['4.3'], sectionLabel: 'Critical Values & Absolute Mins&Maxes',
      title: '4.3 Critical Values & Absolute Mins&Maxes (Blended/Honors)', desc: 'Extended Blended/Honors practice set covering critical values & absolute mins&maxes.',
      worksheetFile: 'Course Materials/Calc 1/Blended Sessions/Unit 3/4.3 Critical Values & Absolute Mins&Maxes.pdf', solutionsFile: 'Course Materials/Calc 1/Blended Sessions/Unit 3/4.3 Critical Values & Absolute Mins&Maxes_Solutions.pdf', updated: '2026-01-05' },
    { id: 'w-c1-4.4-ble', course: 'Calculus I', type: 'Worksheet', subtype: 'Blended', sections: ['4.4'], sectionLabel: 'Fermat\'s Rolle\'s, & MVT',
      title: '4.4 Fermat\'s Rolle\'s, & MVT (Blended/Honors)', desc: 'Extended Blended/Honors practice set covering fermat\'s rolle\'s, & mvt.',
      worksheetFile: 'Course Materials/Calc 1/Blended Sessions/Unit 3/4.4 Fermat\'s Rolle\'s, & MVT.pdf', solutionsFile: 'Course Materials/Calc 1/Blended Sessions/Unit 3/4.4 Fermat\'s Rolle\'s, & MVT_Solutions.pdf', updated: '2026-02-02' },
    { id: 'w-c1-4.5-ble', course: 'Calculus I', type: 'Worksheet', subtype: 'Blended', sections: ['4.5'], sectionLabel: 'Anaylzing Functions',
      title: '4.5 Anaylzing Functions (Blended/Honors)', desc: 'Extended Blended/Honors practice set covering anaylzing functions.',
      worksheetFile: 'Course Materials/Calc 1/Blended Sessions/Unit 3/4.5 Anaylzing Functions.pdf', solutionsFile: 'Course Materials/Calc 1/Blended Sessions/Unit 3/4.5 Anaylzing Functions_Solutions.pdf', updated: '2026-01-19' },
    { id: 'w-c1-4.7-ble', course: 'Calculus I', type: 'Worksheet', subtype: 'Blended', sections: ['4.7'], sectionLabel: 'Optimization',
      title: '4.7 Optimization (Blended/Honors)', desc: 'Extended Blended/Honors practice set covering optimization.',
      worksheetFile: 'Course Materials/Calc 1/Blended Sessions/Unit 3/4.7 Optimization.pdf', solutionsFile: 'Course Materials/Calc 1/Blended Sessions/Unit 3/4.7 Optimization_Solutions.pdf', updated: '2026-02-16' },
    { id: 'w-c1-sc3-ble', course: 'Calculus I', type: 'Worksheet', subtype: 'Blended', sections: ['4.0'], sectionLabel: 'Skills Check 3',
      title: 'Skills Check 3 (Blended/Honors)', desc: 'Blended/Honors practice and solutions for Skills Check 3.',
      worksheetFile: 'Course Materials/Calc 1/Blended Sessions/Unit 3/Skills Check 3.pdf', solutionsFile: 'Course Materials/Calc 1/Blended Sessions/Unit 3/Skills Check 3_Solutions.pdf', updated: '2026-03-16' },
    { id: 'w-c1-5.1-ble', course: 'Calculus I', type: 'Worksheet', subtype: 'Blended', sections: ['5.1'], sectionLabel: 'Reimann sums',
      title: '5.1 Reimann sums (Blended/Honors)', desc: 'Extended Blended/Honors practice set covering reimann sums.',
      worksheetFile: 'Course Materials/Calc 1/Blended Sessions/Unit 4/5.1 Reimann sums.pdf', solutionsFile: 'Course Materials/Calc 1/Blended Sessions/Unit 4/5.1 Reimann sums_Solutions.pdf', updated: '2026-01-05' },
    { id: 'w-c1-5.2-5.3-ble', course: 'Calculus I', type: 'Worksheet', subtype: 'Blended', sections: ['5.2', '5.3'], sectionLabel: 'Different Approaches & FTC',
      title: '5.2 & 5.3 Different Approaches & FTC (Blended/Honors)', desc: 'Extended Blended/Honors practice set covering different approaches & ftc.',
      worksheetFile: 'Course Materials/Calc 1/Blended Sessions/Unit 4/5.2 - 5.3 3 Different Approaches & FTC.pdf', solutionsFile: 'Course Materials/Calc 1/Blended Sessions/Unit 4/5.2 - 5.3 3 Different Approaches & FTC_Solutions.pdf', updated: '2026-02-02' },
    { id: 'w-c1-5.2.1-ble', course: 'Calculus I', type: 'Worksheet', subtype: 'Blended', sections: ['5.2.1'], sectionLabel: 'Definite Integrals',
      title: '5.2.1 Definite Integrals (Blended/Honors)', desc: 'Extended Blended/Honors practice set covering definite integrals.',
      worksheetFile: 'Course Materials/Calc 1/Blended Sessions/Unit 4/5.2.1 Definite Integrals.pdf', solutionsFile: 'Course Materials/Calc 1/Blended Sessions/Unit 4/5.2.1 Definite Integrals_Solutions.pdf', updated: '2026-01-19' },
    { id: 'w-c1-5.2.2-5.2.3-ble', course: 'Calculus I', type: 'Worksheet', subtype: 'Blended', sections: ['5.2.2', '5.2.3'], sectionLabel: 'Properties of Integrals & Avg. Value',
      title: '5.2.2 & 5.2.3 Properties of Integrals & Avg. Value (Blended/Honors)', desc: 'Extended Blended/Honors practice set covering properties of integrals & avg. value.',
      worksheetFile: 'Course Materials/Calc 1/Blended Sessions/Unit 4/5.2.2 & 5.2.3 Properties of Integrals & Avg. Value.pdf', solutionsFile: 'Course Materials/Calc 1/Blended Sessions/Unit 4/5.2.2 & 5.2.3 Properties of Integrals & Avg. Value_Solutions.pdf', updated: '2026-02-16' },
    { id: 'w-c1-5.3.1-ble', course: 'Calculus I', type: 'Worksheet', subtype: 'Blended', sections: ['5.3.1'], sectionLabel: 'The Fundamental Theorem of Calculus',
      title: '5.3.1 The Fundamental Theorem of Calculus (Blended/Honors)', desc: 'Extended Blended/Honors practice set covering the fundamental theorem of calculus.',
      worksheetFile: 'Course Materials/Calc 1/Blended Sessions/Unit 4/5.3.1 The Fundamental Theorem of Calculus.pdf', solutionsFile: 'Course Materials/Calc 1/Blended Sessions/Unit 4/5.3.1 The Fundamental Theorem of Calculus_Solutions.pdf', updated: '2026-03-16' },
    { id: 'w-c1-5.5-ble', course: 'Calculus I', type: 'Worksheet', subtype: 'Blended', sections: ['5.5'], sectionLabel: 'Integration by Substitution',
      title: '5.5 Integration by Substitution (Blended/Honors)', desc: 'Extended Blended/Honors practice set covering integration by substitution.',
      worksheetFile: 'Course Materials/Calc 1/Blended Sessions/Unit 4/5.5 Integration by Substitution.pdf', solutionsFile: 'Course Materials/Calc 1/Blended Sessions/Unit 4/5.5 Integration by Substitution_Solutions.pdf', updated: '2026-01-05' },
    { id: 'w-c1-course-review-ble', course: 'Calculus I', type: 'Worksheet', subtype: 'Blended', sections: ['0.999'], sectionLabel: 'Course Review', resource: true,
      title: 'Course Review (Blended/Honors)', desc: 'Cumulative Blended/Honors course review packet and solutions.',
      worksheetFile: 'Course Materials/Calc 1/Blended Sessions/Course Review/Course Review.pdf', solutionsFile: 'Course Materials/Calc 1/Blended Sessions/Course Review/Course Review_Solutions.pdf', updated: '2026-01-19' },
    { id: 'v-c1-2.2', course: 'Calculus I', type: 'LectureVideo', sections: ['2.2'], sectionLabel: 'Limits (An Intuitive Approach)',
      title: '2.2 Limits (An Intuitive Approach) — Lecture Videos', desc: 'Recorded walkthroughs covering limits (an intuitive approach).',
      playlistUrl: 'https://www.youtube.com/playlist?list=PL6m9J__7h5X09mEUgraWAPWtDc5rbOZ4W', updated: '2026-02-09' },
    { id: 'v-c1-2.3.1', course: 'Calculus I', type: 'LectureVideo', sections: ['2.3.1'], sectionLabel: 'Computing Limits',
      title: '2.3.1 Computing Limits — Lecture Videos', desc: 'Recorded walkthroughs covering computing limits.',
      playlistUrl: 'https://www.youtube.com/playlist?list=PL6m9J__7h5X3i0u02IpxKNN6TOp-Fizf5', updated: '2026-02-09' },
    { id: 'v-c1-2.3.2', course: 'Calculus I', type: 'LectureVideo', sections: ['2.3.2'], sectionLabel: 'Limits at Infinity',
      title: '2.3.2 Limits at Infinity — Lecture Videos', desc: 'Recorded walkthroughs covering limits at infinity.',
      playlistUrl: 'https://www.youtube.com/playlist?list=PL6m9J__7h5X198SM9_36utLCIKLUmihnF', updated: '2026-02-09' },
    { id: 'v-c1-2.4.1', course: 'Calculus I', type: 'LectureVideo', sections: ['2.4.1'], sectionLabel: 'Continuity',
      title: '2.4.1 Continuity — Lecture Videos', desc: 'Recorded walkthroughs covering continuity.',
      playlistUrl: 'https://www.youtube.com/playlist?list=PL6m9J__7h5X217q8TAGGkoGxIjprvsPuC', updated: '2026-02-09' },
    { id: 'v-c1-2.4.2', course: 'Calculus I', type: 'LectureVideo', sections: ['2.4.2'], sectionLabel: 'Intermediate Value Theorem',
      title: '2.4.2 Intermediate Value Theorem — Lecture Videos', desc: 'Recorded walkthroughs covering intermediate value theorem.',
      playlistUrl: 'https://www.youtube.com/playlist?list=PL6m9J__7h5X0YWntg_hP38CeDfHDCZj58', updated: '2026-02-09' },
    { id: 'v-c1-2.5', course: 'Calculus I', type: 'LectureVideo', sections: ['2.5'], sectionLabel: 'Epsilon-Delta Definition of Limits',
      title: '2.5 Epsilon-Delta Definition of Limits — Lecture Videos', desc: 'Recorded walkthroughs covering epsilon-delta definition of limits.',
      playlistUrl: 'https://www.youtube.com/playlist?list=PL6m9J__7h5X1rihBanpSCyn0jIIvLOmP2', updated: '2026-02-09' },
    { id: 'v-c1-3.1', course: 'Calculus I', type: 'LectureVideo', sections: ['3.1'], sectionLabel: 'Defining the Derivative',
      title: '3.1 Defining the Derivative — Lecture Videos', desc: 'Recorded walkthroughs covering defining the derivative.',
      playlistUrl: 'https://www.youtube.com/playlist?list=PL6m9J__7h5X2rCENZZmn9KKh-jT541V_J', updated: '2026-02-09' },
    { id: 'v-c1-3.2', course: 'Calculus I', type: 'LectureVideo', sections: ['3.2'], sectionLabel: 'The Derivative as a Function',
      title: '3.2 The Derivative as a Function — Lecture Videos', desc: 'Recorded walkthroughs covering the derivative as a function.',
      playlistUrl: 'https://www.youtube.com/playlist?list=PL6m9J__7h5X1gpXV3n4wk2_d7Jwzd4DiW', updated: '2026-02-09' },
    { id: 'v-c1-3.3.1', course: 'Calculus I', type: 'LectureVideo', sections: ['3.3.1'], sectionLabel: 'Introduction to Differentiation',
      title: '3.3.1 Introduction to Differentiation — Lecture Videos', desc: 'Recorded walkthroughs covering introduction to differentiation.',
      playlistUrl: 'https://www.youtube.com/playlist?list=PL6m9J__7h5X2CpHa8PNtpGC4IF29cFN2U', updated: '2026-02-09' },
    { id: 'v-c1-3.3.2', course: 'Calculus I', type: 'LectureVideo', sections: ['3.3.2'], sectionLabel: 'The Product Rule',
      title: '3.3.2 The Product Rule — Lecture Videos', desc: 'Recorded walkthroughs covering the product rule.',
      playlistUrl: 'https://www.youtube.com/playlist?list=PL6m9J__7h5X2ZRoLPSivujSu78aJ901Bt', updated: '2026-01-26' },
    { id: 'v-c1-3.3.3', course: 'Calculus I', type: 'LectureVideo', sections: ['3.3.3'], sectionLabel: 'The Quotient Rule',
      title: '3.3.3 The Quotient Rule — Lecture Videos', desc: 'Recorded walkthroughs covering the quotient rule.',
      playlistUrl: 'https://www.youtube.com/playlist?list=PL6m9J__7h5X0qtzdOwAJ8NuCCeROrl4Io', updated: '2026-03-16' },
    { id: 'v-c1-3.5', course: 'Calculus I', type: 'LectureVideo', sections: ['3.5'], sectionLabel: 'Derivatives of Trigonometric Functions',
      title: '3.5 Derivatives of Trigonometric Functions — Lecture Videos', desc: 'Recorded walkthroughs covering derivatives of trigonometric functions.',
      playlistUrl: 'https://www.youtube.com/playlist?list=PL6m9J__7h5X0EwTt39q-ZfHN--mdBZ9oc', updated: '2026-02-09' },
    { id: 'v-c1-3.6', course: 'Calculus I', type: 'LectureVideo', sections: ['3.6'], sectionLabel: 'The Chain Rule',
      title: '3.6 The Chain Rule — Lecture Videos', desc: 'Recorded walkthroughs covering the chain rule.',
      playlistUrl: 'https://www.youtube.com/playlist?list=PL6m9J__7h5X0Xw3h_wx3iROex8ouBMGro', updated: '2026-01-26' },
    { id: 'v-c1-3.8', course: 'Calculus I', type: 'LectureVideo', sections: ['3.8'], sectionLabel: 'Implicit Differentiation',
      title: '3.8 Implicit Differentiation — Lecture Videos', desc: 'Recorded walkthroughs covering implicit differentiation.',
      playlistUrl: 'https://www.youtube.com/playlist?list=PL6m9J__7h5X2_Gbl3P3r1JRVDYI3mcECp', updated: '2026-03-16' },
    { id: 'v-c1-3.9', course: 'Calculus I', type: 'LectureVideo', sections: ['3.9'], sectionLabel: 'Derivatives of Exponential and Logarithmic Functions',
      title: '3.9 Derivatives of Exponential and Logarithmic Functions — Lecture Videos', desc: 'Recorded walkthroughs covering derivatives of exponential and logarithmic functions.',
      playlistUrl: 'https://www.youtube.com/playlist?list=PL6m9J__7h5X3sgzO3fO3XE8KqpqcDCowT', updated: '2026-02-09' },
    { id: 'v-c1-4.1', course: 'Calculus I', type: 'LectureVideo', sections: ['4.1'], sectionLabel: 'Related Rates',
      title: '4.1 Related Rates — Lecture Videos', desc: 'Recorded walkthroughs covering related rates.',
      playlistUrl: 'https://www.youtube.com/playlist?list=PL6m9J__7h5X2YqN5dZJUwN7oT30vAamXK', updated: '2026-01-26' },
    { id: 'v-c1-4.2', course: 'Calculus I', type: 'LectureVideo', sections: ['4.2'], sectionLabel: 'Linear Approximations & Differentials',
      title: '4.2 Linear Approximations & Differentials — Lecture Videos', desc: 'Recorded walkthroughs covering linear approximations & differentials.',
      playlistUrl: 'https://www.youtube.com/playlist?list=PL6m9J__7h5X2DuMrv6iUB2LpI-9Rdvc0m', updated: '2026-03-16' },
    { id: 'v-c1-4.3', course: 'Calculus I', type: 'LectureVideo', sections: ['4.3'], sectionLabel: 'Maximum & Minimum Values',
      title: '4.3 Maximum & Minimum Values — Lecture Videos', desc: 'Recorded walkthroughs covering maximum & minimum values.',
      playlistUrl: 'https://www.youtube.com/playlist?list=PL6m9J__7h5X3wKZZYyfAadxG1njPnjyle', updated: '2026-02-09' },
    { id: 'v-c1-4.4', course: 'Calculus I', type: 'LectureVideo', sections: ['4.4'], sectionLabel: 'The Mean Value Theorem',
      title: '4.4 The Mean Value Theorem — Lecture Videos', desc: 'Recorded walkthroughs covering the mean value theorem.',
      playlistUrl: 'https://www.youtube.com/playlist?list=PL6m9J__7h5X0mRJEwycEF612hknOai-i3', updated: '2026-01-26' },
    { id: 'v-c1-4.5', course: 'Calculus I', type: 'LectureVideo', sections: ['4.5'], sectionLabel: 'Derivatives & the Shape of a Graph',
      title: '4.5 Derivatives & the Shape of a Graph — Lecture Videos', desc: 'Recorded walkthroughs covering derivatives & the shape of a graph.',
      playlistUrl: 'https://www.youtube.com/playlist?list=PL6m9J__7h5X0HNFP_SHDuXuaJ8qziLE9g', updated: '2026-03-16' },
    { id: 'v-c1-4.7', course: 'Calculus I', type: 'LectureVideo', sections: ['4.7'], sectionLabel: 'Optimization',
      title: '4.7 Optimization — Lecture Videos', desc: 'Recorded walkthroughs covering optimization.',
      playlistUrl: 'https://www.youtube.com/playlist?list=PL6m9J__7h5X1_CMlVoPmrD7--GAIRh8F_', updated: '2026-02-09' },
    { id: 'v-c1-4.8', course: 'Calculus I', type: 'LectureVideo', sections: ['4.8'], sectionLabel: 'L\'Hopital\'s Rule; Indeterminate Forms',
      title: '4.8 L\'Hopital\'s Rule; Indeterminate Forms — Lecture Videos', desc: 'Recorded walkthroughs covering l\'hopital\'s rule; indeterminate forms.',
      playlistUrl: 'https://www.youtube.com/playlist?list=PL6m9J__7h5X3qkZ5W8bKSg4IwlnO7k_C6', updated: '2026-01-26' },
    { id: 'v-c1-4.9', course: 'Calculus I', type: 'LectureVideo', sections: ['4.9'], sectionLabel: 'Newton\'s Method',
      title: '4.9 Newton\'s Method — Lecture Videos', desc: 'Recorded walkthroughs covering newton\'s method.',
      playlistUrl: 'https://www.youtube.com/playlist?list=PL6m9J__7h5X2m3edfsTa4X8qBpjNOAaHZ', updated: '2026-03-16' },
    { id: 'v-c1-4.10', course: 'Calculus I', type: 'LectureVideo', sections: ['4.10'], sectionLabel: 'Antiderivatives',
      title: '4.10 Antiderivatives — Lecture Videos', desc: 'Recorded walkthroughs covering antiderivatives.',
      playlistUrl: 'https://www.youtube.com/playlist?list=PL6m9J__7h5X2m9QF5-gffxQCrwnWXIrgE', updated: '2026-02-09' },
    { id: 'v-c1-5.1', course: 'Calculus I', type: 'LectureVideo', sections: ['5.1'], sectionLabel: 'Approximating Areas',
      title: '5.1 Approximating Areas — Lecture Videos', desc: 'Recorded walkthroughs covering approximating areas.',
      playlistUrl: 'https://www.youtube.com/playlist?list=PL6m9J__7h5X2tyX6rj3B16sXwWVn6xerl', updated: '2026-01-26' },
    { id: 'v-c1-5.2.1', course: 'Calculus I', type: 'LectureVideo', sections: ['5.2.1'], sectionLabel: 'The Definite Integral',
      title: '5.2.1 The Definite Integral — Lecture Videos', desc: 'Recorded walkthroughs covering the definite integral.',
      playlistUrl: 'https://www.youtube.com/playlist?list=PL6m9J__7h5X1Tp5gpyBcMNTSW0eVFqX77', updated: '2026-03-16' },
    { id: 'v-c1-5.2.2', course: 'Calculus I', type: 'LectureVideo', sections: ['5.2.2'], sectionLabel: 'Properties of the Definite Integral',
      title: '5.2.2 Properties of the Definite Integral — Lecture Videos', desc: 'Recorded walkthroughs covering properties of the definite integral.',
      playlistUrl: 'https://www.youtube.com/playlist?list=PL6m9J__7h5X2PNY9JTNuEHxJSs4b3jV1Z', updated: '2026-02-09' },
    { id: 'v-c1-5.2.3', course: 'Calculus I', type: 'LectureVideo', sections: ['5.2.3'], sectionLabel: 'Average Value',
      title: '5.2.3 Average Value — Lecture Videos', desc: 'Recorded walkthroughs covering average value.',
      playlistUrl: 'https://www.youtube.com/playlist?list=PL6m9J__7h5X2PK8C3NgGHr0vZ4lzHqSbb', updated: '2026-01-26' },
    { id: 'v-c1-5.3.1', course: 'Calculus I', type: 'LectureVideo', sections: ['5.3.1'], sectionLabel: 'The Fundamental Theorem of Calculus',
      title: '5.3.1 The Fundamental Theorem of Calculus — Lecture Videos', desc: 'Recorded walkthroughs covering the fundamental theorem of calculus.',
      playlistUrl: 'https://www.youtube.com/playlist?list=PL6m9J__7h5X0XdMeMkJO6RdjFgU5dBPmd', updated: '2026-03-16' },
    { id: 'v-c1-5.3.2', course: 'Calculus I', type: 'LectureVideo', sections: ['5.3.2'], sectionLabel: 'Definite & Indefinite Integrals',
      title: '5.3.2 Definite & Indefinite Integrals — Lecture Videos', desc: 'Recorded walkthroughs covering definite & indefinite integrals.',
      playlistUrl: 'https://www.youtube.com/playlist?list=PL6m9J__7h5X3nstPoC9b1PEzCYjRe9nCw', updated: '2026-02-09' },
    { id: 'v-c1-5.5.1', course: 'Calculus I', type: 'LectureVideo', sections: ['5.5.1'], sectionLabel: 'Integration by Substitution (Indefinite Integrals)',
      title: '5.5.1 Integration by Substitution (Indefinite Integrals) — Lecture Videos', desc: 'Recorded walkthroughs covering integration by substitution (indefinite integrals).',
      playlistUrl: 'https://www.youtube.com/playlist?list=PL6m9J__7h5X0fMsOCJ91CHjRqqq6mRfoQ', updated: '2026-01-26' },
    { id: 'v-c1-5.5.2', course: 'Calculus I', type: 'LectureVideo', sections: ['5.5.2'], sectionLabel: 'Integration by Substitution (Definite Integrals)',
      title: '5.5.2 Integration by Substitution (Definite Integrals) — Lecture Videos', desc: 'Recorded walkthroughs covering integration by substitution (definite integrals).',
      playlistUrl: 'https://www.youtube.com/playlist?list=PL6m9J__7h5X1KLmEp_J6kZ9Bj7IBMOeCa', updated: '2026-03-16' },
    { id: 'v-c1-5.4', course: 'Calculus I', type: 'LectureVideo', sections: ['5.4'], sectionLabel: 'Applications of Integration',
      title: '5.4 Applications of Integration — Lecture Videos', desc: 'Recorded walkthroughs covering applications of integration.',
      playlistUrl: 'https://www.youtube.com/playlist?list=PL6m9J__7h5X30SY0KN0_xwYo64cxZmOHb', updated: '2026-02-09' },
    { id: 'v-c1-sc1', course: 'Calculus I', type: 'LectureVideo', sections: ['2.0'], sectionLabel: 'Skills Check 1',
      title: 'Skills Check 1 — Lecture Videos', desc: 'Recorded walkthrough of Skills Check 1 practice problems.',
      playlistUrl: 'https://www.youtube.com/playlist?list=PL6m9J__7h5X3hOozTZAswiO3Y0oCMB-F3', updated: '2026-01-26' },
    { id: 'v-c1-sc2', course: 'Calculus I', type: 'LectureVideo', sections: ['3.0'], sectionLabel: 'Skills Check 2',
      title: 'Skills Check 2 — Lecture Videos', desc: 'Recorded walkthrough of Skills Check 2 practice problems.',
      playlistUrl: 'https://www.youtube.com/playlist?list=PL6m9J__7h5X3QtOsGV0628G8qqqBkrmA4', updated: '2026-03-16' },
    { id: 'v-c1-sc3', course: 'Calculus I', type: 'LectureVideo', sections: ['4.0'], sectionLabel: 'Skills Check 3',
      title: 'Skills Check 3 — Lecture Videos', desc: 'Recorded walkthrough of Skills Check 3 practice problems.',
      playlistUrl: 'https://www.youtube.com/playlist?list=PL6m9J__7h5X0b5chUcrfwj3bYcfSL_x8K', updated: '2026-02-09' },

    { id: 'g-c2-34', course: 'Calculus II', type: 'LectureGuideNotes', sections: ['3.4'], sectionLabel: 'Series Convergence',
      title: '3.4 Series Convergence — Guide & Notes', desc: 'Guide and notes covering convergence tests for infinite series.',
      guideFile: '#', notesFile: '#', updated: '2026-06-18' },
    { id: 'w-c2-34-std', course: 'Calculus II', type: 'Worksheet', subtype: 'Standard', sections: ['3.4'], sectionLabel: 'Series Convergence',
      title: '3.4 Series Convergence Worksheet', desc: 'Practice applying the ratio, root, and comparison tests.',
      worksheetFile: '#', solutionsFile: '#', updated: '2026-06-25' },
    { id: 'v-c2-34', course: 'Calculus II', type: 'LectureVideo', sections: ['3.4'], sectionLabel: 'Series Convergence',
      title: '3.4 Series Convergence — Lecture Videos', desc: 'Recorded lecture covering convergence tests with worked examples.',
      playlistUrl: '#', updated: '2026-07-16' },

    { id: 'g-c3-52', course: 'Calculus III', type: 'LectureGuideNotes', sections: ['5.2'], sectionLabel: 'Triple Integrals',
      title: '5.2 Triple Integrals — Guide & Notes', desc: 'Guide and notes on setting up triple integrals in rectangular coordinates.',
      guideFile: '#', notesFile: '#', updated: '2026-05-02' },
    { id: 'w-c3-52-std', course: 'Calculus III', type: 'Worksheet', subtype: 'Standard', sections: ['5.2'], sectionLabel: 'Triple Integrals',
      title: '5.2 Triple Integrals Worksheet', desc: 'Standard practice setting up and evaluating triple integrals.',
      worksheetFile: '#', solutionsFile: '#', updated: '2026-01-12' },
    { id: 'w-c3-52-ble', course: 'Calculus III', type: 'Worksheet', subtype: 'Blended', sections: ['5.2'], sectionLabel: 'Triple Integrals',
      title: '5.2 Triple Integrals Worksheet (Blended/Honors)', desc: 'Extended practice including cylindrical and spherical setups.',
      worksheetFile: '#', solutionsFile: '#', updated: '2026-03-28' },
    { id: 'v-c3-52', course: 'Calculus III', type: 'LectureVideo', sections: ['5.2'], sectionLabel: 'Triple Integrals',
      title: '5.2 Triple Integrals — Lecture Videos', desc: 'Recorded walkthroughs of triple integral setup and evaluation.',
      playlistUrl: '#', updated: '2026-03-01' },

    { id: 'g-c3-41', course: 'Calculus III', type: 'LectureGuideNotes', sections: ['4.1'], sectionLabel: 'Quadric Surfaces',
      title: '4.1 Quadric Surfaces — Guide', desc: 'Guide to identifying and sketching quadric surfaces from their equations.',
      guideFile: '#', notesFile: null, updated: '2026-05-20' },
    { id: 'a-c3-41', course: 'Calculus III', type: 'Applet', sections: ['4.1'],
      title: 'Quadric Surfaces Explorer', desc: 'Interactive tool for rotating and slicing quadric surfaces to see their cross-sections.',
      curve: 'M14,52 C34,14 56,14 74,32 S 100,52 118,22', launchUrl: '#', updated: '2026-07-14' },

    { id: 'g-pc-12', course: 'Precalculus', type: 'LectureGuideNotes', sections: ['1.2'], sectionLabel: 'The Unit Circle',
      title: '1.2 The Unit Circle — Guide & Notes', desc: 'Guide and notes on unit circle values and their use in trigonometric functions.',
      guideFile: '#', notesFile: '#', updated: '2026-03-05' },
    { id: 'a-pc-12', course: 'Precalculus', type: 'Applet', sections: ['1.2'],
      title: 'Unit Circle Explorer', desc: 'Drag a point around the unit circle to see corresponding sine and cosine values update live.',
      curve: 'M14,32 C30,10 60,10 74,32 S 105,55 118,32', launchUrl: '#', updated: '2026-04-11' },

    { id: 'g-st-61', course: 'Statistics', type: 'LectureGuideNotes', sections: ['6.1'], sectionLabel: 'Hypothesis Testing',
      title: '6.1 Hypothesis Testing — Notes', desc: 'Notes introducing null/alternative hypotheses, p-values, and significance levels.',
      guideFile: null, notesFile: '#', updated: '2026-02-20' },
    { id: 'w-st-61-std', course: 'Statistics', type: 'Worksheet', subtype: 'Standard', sections: ['6.1'], sectionLabel: 'Hypothesis Testing',
      title: '6.1 Hypothesis Testing Worksheet', desc: 'Practice setting up and interpreting hypothesis tests.',
      worksheetFile: '#', solutionsFile: '#', updated: '2026-02-14' },

    { id: 'g-la-31', course: 'Linear Algebra', type: 'LectureGuideNotes', sections: ['3.1'], sectionLabel: 'Eigenvalues & Eigenvectors',
      title: '3.1 Eigenvalues & Eigenvectors — Guide & Notes', desc: 'Guide and notes on computing eigenvalues and eigenvectors of a matrix.',
      guideFile: '#', notesFile: '#', updated: '2026-01-30' },
    { id: 'a-la-31', course: 'Linear Algebra', type: 'Applet', sections: ['3.1', '3.2'],
      title: 'Eigenvalues & Eigenvectors Explorer', desc: 'Visualize how a matrix transforms vectors and highlights its eigenvectors.',
      curve: 'M14,45 C40,50 55,15 74,20 S 105,45 118,15', launchUrl: '#', updated: '2026-05-20' },

    { id: 'w-dm-21-std', course: 'Discrete', type: 'Worksheet', subtype: 'Standard', sections: ['2.1'], sectionLabel: 'Logic & Proofs',
      title: '2.1 Logic & Proofs Worksheet', desc: 'Practice with truth tables, logical equivalences, and basic proof techniques.',
      worksheetFile: '#', solutionsFile: '#', updated: '2026-01-05' },
  ];

  // ---------- v16: dummy data — 10 items per unit per material type, 5 units, Calculus I & Calculus III (~400 items) ----------
  const dummyUnitDefs = {
    'Calculus III': [
      { unit: 1, label: 'Vectors in 3D Space' },
      { unit: 2, label: 'Partial Derivatives' },
      { unit: 3, label: 'Directional Derivatives & Gradients' },
      { unit: 6, label: 'Line Integrals' },
      { unit: 7, label: 'Surface Integrals' },
    ]
  };
  const subtopicSuffixes = ['Part A', 'Part B', 'Part C', 'Part D', 'Part E', 'Part F', 'Part G', 'Part H', 'Part I', 'Part J'];

  function buildDummyItems() {
    const out = [];
    const dates = ['2026-01-08', '2026-02-12', '2026-03-05', '2026-04-18', '2026-05-22', '2026-06-14', '2026-07-20', '2026-07-25', '2026-01-30', '2026-06-01'];
    let dateIdx = 0;
    const nextDate = () => dates[(dateIdx++) % dates.length];

    Object.keys(dummyUnitDefs).forEach(course => {
      const cs = course === 'Calculus I' ? 'c1' : 'c3';
      dummyUnitDefs[course].forEach(block => {
        for (let n = 1; n <= 10; n++) {
          const sec = `${block.unit}.${n}`;
          const secId = `${block.unit}-${n}`;
          const suffix = subtopicSuffixes[n - 1];
          const subtype = (n % 2 === 0) ? 'Blended' : 'Standard';
          out.push({ id: `d-${cs}-${secId}-ws`, course, type: 'Worksheet', subtype,
            sections: [sec], sectionLabel: `${block.label} — ${suffix}`,
            title: `${sec} ${block.label} Worksheet${subtype === 'Blended' ? ' (Blended/Honors)' : ''}`,
            desc: `Practice set covering ${block.label.toLowerCase()}, ${suffix.toLowerCase()}.`,
            worksheetFile: '#', solutionsFile: '#', updated: nextDate() });
          out.push({ id: `d-${cs}-${secId}-lgn`, course, type: 'LectureGuideNotes',
            sections: [sec], sectionLabel: `${block.label} — ${suffix}`,
            title: `${sec} ${block.label} — Guide & Notes (${suffix})`,
            desc: `Guide and notes covering ${block.label.toLowerCase()}, ${suffix.toLowerCase()}.`,
            guideFile: '#', notesFile: '#', updated: nextDate() });
          out.push({ id: `d-${cs}-${secId}-vid`, course, type: 'LectureVideo',
            sections: [sec], sectionLabel: `${block.label} — ${suffix}`,
            title: `${sec} ${block.label} — Lecture Video (${suffix})`,
            desc: `Recorded walkthrough of ${block.label.toLowerCase()}, ${suffix.toLowerCase()}.`,
            playlistUrl: '#', updated: nextDate() });
          out.push({ id: `d-${cs}-${secId}-app`, course, type: 'Applet',
            sections: [sec],
            title: `${block.label} Explorer (${suffix})`,
            desc: `Interactive exploration tool for ${block.label.toLowerCase()}, ${suffix.toLowerCase()}.`,
            curve: 'M14,50 C34,20 56,45 74,25 S 100,45 118,20', launchUrl: '#', updated: nextDate() });
        }
      });
    });
    return out;
  }
  items.push(...buildDummyItems());

  const courseOrder = ["Precalculus", "Calculus I", "Calculus II", "Calculus III", "Linear Algebra", "Discrete", "Statistics"];
  const typeOrder = ["Applet", "Worksheet", "LectureGuideNotes", "LectureVideo"];
  const typeLabel = { Applet: "Applets", Worksheet: "Worksheets", LectureGuideNotes: "Lecture Guides/Notes", LectureVideo: "Lecture Videos" };
